"""
Defines the shared state object for the LangGraph agent pipeline.
"""
from typing import List, Dict, Any, TypedDict, Optional

class AgentState(TypedDict):
    """Represents the state of our agent graph."""
    original_question: str
    clarified_question: str
    plan_outline: str # Markdown outline generated by clarifier/planner stage
    search_results: List[Dict[str, Any]] # Raw results from search (may become intermediate in reasoner)
    rag_context: str # Context retrieved from RAG (may become intermediate in reasoner)
    rag_source_paths: List[str] # Source paths from RAG (may become intermediate in reasoner)
    combined_context: str
    final_answer: str
    web_source_urls: List[str]
    verbosity_level: int
    error: Optional[str] # To capture errors within the graph flow